name = "arden-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENV = "development"

[[d1_databases]]
binding = "DB"
database_name = "arden-db"
database_id = "3bbd1486-85f2-4b83-862b-f4522abd194e"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "ARDEN_REFRESH_TOKEN_KV"
id = "0e4eb9cb47034089b9ce9dc30bf1e902"

[observability.logs]
enabled = true
