name: Biome Linting & Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  biome:
    name: Run Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Biome check
        run: bunx biome ci
